In [ ]:
'''
Write a Python Program to Get 5 Student Name with their Marks and
Display Student Name and their Marks in Key Value Form.
'''
students = {
    'Tamim':59,
    'Sajib':50,
    'shawon':30,
    'Rona':55,
    'karim':90
}
for key,value in students.items():
    print(key," ",value)

Tamim   59
Sajib   50
shawon   30
Rona   55
karim   90

In [ ]:
'''
Write a Python Program to Get 5 Digital Product and their Price.
Display Total Price of the Products.
'''
product = {

}

In [ ]:
a = {3,5,6}
b = {5,2,7}
c = a.union(b)

print(c)

{2, 3, 5, 6, 7}

add a new item in to  a set

In [ ]:
set_a = {10, 2, 3}
num = int(input('Num: '))

# Create set_b correctly
set_b = {num}  # set_b should be a set, not a dictionary
# Add num to set_a using union (or you could use update)
set_a = set_a.union(set_b)  # This returns a new set, so we assign it to set_a

# Alternatively, you could use the update method like this:
# set_a.update(set_b)

print(set_a)

Num: 80
{2, 80, 10, 3}

In [ ]:
set_a.clear()

set_a.add(10)

print(set_a)

{10}

In [ ]:
my_set = set()
for i in range(1,6,1):
    name  = input('Input name: ')
    my_set.add(name)
print(my_set)

In [ ]:
a = {3,5,6}
b = {5,2,7}
c = a.union(b)
d = a.intersection(b)
print(c)
f = c.difference(d)
print(d)
print(f)

{2, 3, 5, 6, 7}
{5}
{2, 3, 6, 7}

In [ ]:
a = {1,2,3,4,5}
b = {10,11,12,13,1,1,2}
c = a.intersection(b)
print(c)

{1, 2}